[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
learnway = "4PPXwojpTCyAvCf2A9WerJr51H6bF9dT7qdPQeLwxukx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/gloryagatevure/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
